[
package
]
name = "pdtp"
version = "0.1.0"
description = "A Tauri App"
authors = ["Pyditn"]
edition = "2024"

[
lib
]
name = "pdtp_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[
build-dependencies
]
tauri-build = { version = "2", features = [] }

[
dependencies
]
tauri = { version = "2", features = ["shell-all"] }
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[
features
]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]

# Optimize release builds
[
profile.release
]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true