name: Build PDTP
on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      
      # Force Rust to use static linking for Windows
      - name: Set Windows environment
        if: matrix.platform == 'windows-latest'
        run: |
          echo "RUSTFLAGS=-C target-feature=+crt-static" >> $GITHUB_ENV
        shell: bash

      - name: Install dependencies
        run: npm install
        
      - name: Install Tauri CLI
        run: cargo install tauri-cli
        
      # Build Vue.js app
      - name: Build Frontend
        run: npm run build
        env:
          NODE_ENV: production
          
      # Build Tauri app using cargo directly
      - name: Build Tauri (Windows)
        if: matrix.platform == 'windows-latest'
        run: |
          cd src-tauri
          cargo build --release
        env:
          RUST_BACKTRACE: 1
          
      - name: Build Tauri (macOS)
        if: matrix.platform == 'macos-latest'
        run: |
          cd src-tauri
          cargo build --release
        env:
          MACOSX_DEPLOYMENT_TARGET: "10.13"
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: PDTP-${{ matrix.platform }}
          path: |
            src-tauri/target/release/pdtp.exe
            src-tauri/target/release/bundle/macos/PDTP.app